### ISSUE TITLE
Public gem hosting solution

### ISSUE THREAD

**Issue by jeantristan** [fast-jsonapi/fast_jsonapi#81]
## Expected Behavior

I would like to install the gem using `bundle install`

## Actual Behavior

I added in my Gemfile the following line: `gem 'fast_jsonapi', source: 'https://rubygems.pkg.github.com/fast-jsonapi'`

When trying to do `bundle install`on my local machine, I have the following problem:
```
       Authentication is required for rubygems.pkg.github.com.

       Please supply credentials for this source. You can do this by running:

        bundle config set rubygems.pkg.github.com username:password
```
I have the same output on a heroku instance.
It only happen with this gem.

On top of that, trying to go on `https://rubygems.pkg.github.com/fast-jsonapi`with my browser I have the following error: `404 page not found`

## Steps to Reproduce the Problem

  1. Add the gem to Gemfile
  2. BUndle install

## Specifications

  - Version: last stable version

**Comment by stas** [comment]
Oh Github :facepalm:, this is silly, but apparently Github requires authenticated requests to the Package Registry...

@jeantristan thanks for reporting this, I'll look into a solution. Apologies...

**Comment by jeantristan** [comment]
No worries! Thanks for the fork. 
I was looking for a better handling of the cache than the orignal package.
Good luck dealing with the problem!

Do you know if it's possible for me to do a local install or do I have to switch back to the netflix version?

**Comment by stas** [comment]
@jeantristan you can switch back to the git-based deployments (ab9db291d4d89ed93029f0844461498364d3be3b)

Basically use this
```
 gem 'fast_jsonapi', '~> 1.7.1', git: 'https://github.com/fast-jsonapi/fast_jsonapi'
```

**Comment by jeantristan** [comment]
thanks!

**Comment by stas** [comment]
I reverted to the old instructions for now: ac34aa22f7882f54cb7cab352489930c012e1e1b

We will look into alternatives...

**Comment by ToadJamb** [comment]
Assuming it is not possible to get control of `fast_jsonapi` from rubygems, could this just be pushed to rubygems under a new package name? Given that the existing solution is to pull from github anyway, this should have minimal (if any) impact on existing projects.

We currently have `fast_jsonapi` required in a gemspec which means we are using an unsupported version because if it comes from anything other than a public gem server (preferably rubygems), we can't specify and manage versions properly via the gemspec. The current implementation (i.e. no availability via a public gem server) means all of our downstream projects would also have to have some sort of requirement in the Gemfile and that's not tenable for us.

It seems like the easy solution is just to push it to rubygems under a new name. The new gemfile requirement would be something like `gem 'new_fast_jsonapi`, '~> 1.7.1', :require => 'fast_jsonapi'`. What am I missing?

**Comment by stas** [comment]
@ToadJamb I'm not a big fan of a new name since there are other gems depending on it.

I'm open to renaming it, but this suggests we should completely change the name and move away from Neftlix name to avoid confusion. My idea was just to provide a new repository name/source (probably using gemfury.com) and  let the bundler figure out the versions.

Alternatively we just focus on the next release to make it a new independent and clean project...

**Comment by ahx** [comment]
>  […] completely change the name and move away from Neftlix name to avoid confusion

Yes, please! I cannot state how important this is to keep the project alive. I am curious what new name you come up with. Any name is good, really :). You are doing great. Thanks for the fork.

**Comment by stas** [comment]
@jopotts @kpheasey renaming the gem is as much effort as moving to a completely new name and I'd rather do the later than a _quickfix_. What do you think?

**Comment by kpheasey** [comment]
@stas I'm a fan of the gemspec rename with a redirect.  It keeps the project alive in the more popular ruby registry.  

Authenticating with github cli seems like a steep requirement lol.  I know it's not the most effort, but I've never had to do it before.

The approach is simple to how `bundle` installs `bundler`.

**Comment by stas** [comment]
> @stas I'm a fan of the gemspec rename with a redirect. It keeps the project alive in the more popular ruby registry.

@kpheasey what do you mean by this? I'm not sure we can redirect anything by ourselves, could you explain please?

**Comment by kpheasey** [comment]
It's not a real redirect, just similar in idea. We still have to use the Gemfile snippet that @ToadJamb posted above, but at least it doesn't require authentication.

 The current authentication breaks most containers.

**Comment by stas** [comment]
> It seems like the easy solution is just to push it to rubygems under a new name. The new gemfile requirement would be something like `gem 'new_fast_jsonapi', '~> 1.7.1', :require => 'fast_jsonapi'`. What am I missing?

This can break dependencies and will fetch both versions as far as it looks like. What we have (as far as I can see) is either set up a gem on different package repository or rename everything and use rubygems....

**Comment by kpheasey** [comment]
We would only need to change this line https://github.com/fast-jsonapi/fast_jsonapi/blob/master/fast_jsonapi.gemspec#L7

**Comment by stas** [comment]
I don't find the idea of changing the name into something like `new_fast_jsonapi` very appealing. As I mentioned, I think we should pick a proper new name if go for this effort. There are already [other gems] depending on `fast_jsonapi` and asking them to rename their deps for something like `new_fast_jsonapi` is already plenty of effort. So if Netflix comes back and wants us to change the name, we'd have to do it again all-over...

I'd rename it into something relevant, and actually drop the whole _fast_ thing, since that's a bit of an egocentric name lol (i.e. `jsonapi-serializer` seems free and looks pretty representative). Obviously if we are all on the same page of not using an alternative gem hosting/repository.

[other gems]: https://rubygems.org/gems/fast_jsonapi/reverse_dependencies

**Comment by ahx** [comment]
> jsonapi-serializer seems free

Note that jsonapi-serializers (with an s at the end) is taken. And it’s a really good library, too!

**Comment by kpheasey** [comment]
@stas Sorry, I misinterpreted your previous messages and thought you didn't want to rename at all.

What about `fast-jsonapi`.  It would only require renaming the gemspec, it's free on rubygems, and it maintains compatibility for anyone upgrading from fast_jsonapi.

**Comment by stas** [comment]
> So if Netflix comes back and wants us to change the name, we'd have to do it again all-over...

I'm really concerned about Netflix and what they plan to do here, since they are just silent and they have all the rights to demand us not use `fast-/_jsonapi`. Not to mention that it's just all super confusing (and kinda silly to still state that we're always going to be the _fast_ implementation). Again, if we're actually going to put all this effort, I'd like us to leave the @Netflix related details behind as much as possible...

**Comment by kpheasey** [comment]
Netflix can't make us change the name.  It's a fork of a public repository that is then hosted under a different name.  Rubygems doesn't enforce copyright claims on gem names and the project was public on GitHub, so there is no repercussions from any service.

Naming it `fast-jsonap`i will ensure users can switch over easily, it can be found easily, and only requires changing a single line of code before pushing to rubygems (1 minute of work).

If you feel that we need to completely rebrand the gem, then that's a bigger project and will likely require all implementations to replace `FastJsonapi` module references with whatever the new name is.  That's more work in the end.

Let's move forward with `fast-jsonapi` for now, since it doesn't require any work.  If a rebranding is done, that can be released in v2.

**Comment by stas** [comment]
@kpheasey I'm not a lawyer, but I would not like somebody to keep the name of my _forked_ project for many (obvious reasons). It's both, unethical and potentially getting us in trouble due to the naming confusion that other users can keep blaming Netflix for bad releases!

A quick google search, clearly suggests *changing the name* after you fork is the right way to do it:
https://jamesdixon.wordpress.com/forking-protocol-why-when-and-how-to-fork-an-open-source-project/
https://opensource.guide/starting-a-project/#avoiding-name-conflicts
https://fossmarks.org/post/2choosingname/
https://www.g-loaded.eu/2011/03/01/forking-apache-licensed-software-on-github-and-bitbucket/

So yep, I'm not excited about keeping the current name in any way and I really think we should not go that way!

**Comment by kpheasey** [comment]
Ok, let's not go that way in the future.  But in the interim, let's just call it fast-jsonapi so users don't need to authenticate their servers with github to install it using the recommended installation instructions.  

Once we figure out a name, rebrand the gem, and add migration instructions for users to change from `FastJsonapi`, then we can officially rename it.  You are right in assuming there is a lot of effort needed to do that.  Right now though, it's just a matter of making things work and that effort has already been done, (#84).

The only suggested name is `jsonapi-serializer` which conflicts with `jsonapi_serializer` which forks `fast_jsonapi`.  Do you have any suggestions for the name?

**Comment by jits** [comment]
Renaming this fork to `fast-jsonapi` is not a good idea, for all the reasons @stas has already given and, if I may add:

https://guides.rubygems.org/name-your-gem/

It breaks expectations and makes things more confusing.

If it was quick to rename this from `fast_jsonapi` --> `fast-jsonapi` then isn't it quick enough to rename it to anything else?

Also note the licensing terms of Netflix's original work – 
https://github.com/Netflix/fast_jsonapi/blob/master/LICENSE.txt – and bear in mind it's restrictions, e.g. see the points made in https://resources.whitesourcesoftware.com/blog-whitesource/top-10-apache-license-questions-answered

**Comment by kpheasey** [comment]
No, it’s not quick enough to rename it to anything else. If the module name changes from `FastJsonapi` to `NewModule`, then it’s a big change and requires everyone to update their implementations.

**Comment by stas** [comment]
@kpheasey to be honest, I don't understand the rush. We've been in this _limbo_ for a while and if I'd have to pick a fast solution, I'd set up a gemfury repo and host it there :see_no_evil: 

Though even the way it is right now, folks can use it, not ideally, but pretty easily. So I think we should really not rush anywhere here...

**Comment by kpheasey** [comment]
@stas Agreed, let's just not rename it and continue to use the following installation.

```
gem 'fast_jsonapi', '~> 1.7.1', github: 'fast-jsonapi/fast_jsonapi'
```

**Comment by jits** [comment]
> No, it’s not quick enough to rename it to anything else. If the module name changes from `FastJsonapi` to `NewModule`, then it’s a big change and requires everyone to update their implementations.

You could still provide a special compatibility module that needs to be required manually, which just does something this under the hood:

```ruby
FastJsonapi = MyNewSuperDuperJsonModule
```

(I haven't tested this out specifically but the principle of providing a compatibility module still stands).

**Comment by stas** [comment]
Please leave your name suggestions #86
